- name: create user with var prompt
  hosts: all
  vars_prompt:
   - name: uname
     promt: Enter user to create user
     private: false
  tasks:
   - name: Create user with var prompt
     user:
      name: "{{uname}}"
      state: present
     register: ucr
   - name: user debug module to print user id
     debug:
      var: ucr
      # msg:
      # - "the uid of {{uname}} is {{ucr.uid}}" 
