- name: Install Packge using loops
  hosts: node2
  tasks:
   - name: Install Multiple package using look
     dnf:
      name: "{{item}}"
      state: latest
     loop:
      - lsof
      - telnet
      - dialog
      - httpd
      



        