- name: Gather facts from the managed nodes
  hosts: all
  tasks: 
   - name: use Setup module to gather facts
     setup:
     register: facts
   - name: use debug modul to print facts
     debug: 
      #var: facts
      msg: 
       - "the sysytem is running with {{ansible_distribution}} {{ansible_distribution_version}}"
       - "the hostname of the server is {{}}"
       - "the ip address of the server is {{facts.ansible_facts.ansible_default_ipv4.addresses}}"
