- name: Gather facts from the managed nodes
  hosts: all
  gather_facts: false
  tasks: 
   - name: use Setup module to gather facts
     setup:
      gather_subset:  all_ipv4_addresses
     register: facts
   - name: use debug modul to print facts
     debug: 
      #var: facts
      msg: 
        #- "the sysytem is running with {{ansible_distribution}} {{ansible_distribution_version}}"
        #- "the  server hostname is {{ansible_nodename}}"
        - "the server ip is {{facts.ansible_default_ipv4.address}}"